### ISSUE TITLE
[funny] the creator fucking sucks

### ISSUE THREAD

**Issue by DashLt** [BiosPlus/SelfHosted-Music-Bot#1]
fuck me

**Comment by BiosPlus** [comment]
fuck you dash

**Comment by mc2squared** [comment]
hello yes I’m having the same issue, the creator fucking sucks

**Comment by BiosPlus** [comment]
Thanks for all the feedback @DashLt @mc2squared . I'm locking this thread as we've gotten sufficient feedback and the conversation is bordering on being not useful. Please stop being mean.

![371-3710165_135kib-700x710-wojak-crying-sony](https://user-images.githubusercontent.com/9003059/60676497-5ea18b00-9ec2-11e9-8381-df42ef522c77.png)
